# Generated by Django 2.2.17 on 2020-11-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawisata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datawisata',
        ),
    ]
