# Generated by Django 2.2.17 on 2020-11-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datawisata',
            name='id_wisata',
        ),
    ]
