# Generated by Django 2.2.17 on 2020-11-12 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201112_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=9)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='datawisata',
            name='lokasi',
        ),
        migrations.AddField(
            model_name='datawisata',
            name='jml_pengunjung',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datawisata',
            name='jenis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Jenis'),
        ),
    ]
