# Generated by Django 2.2.17 on 2020-11-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201112_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawisata',
            name='jml_pengunjung',
            field=models.IntegerField(null=True),
        ),
    ]
