# Generated by Django 2.2.17 on 2020-11-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201112_0353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datawisata',
        ),
        migrations.DeleteModel(
            name='Jenis',
        ),
    ]
